Week_9/Day 1/account_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.accounts, name='accounts'),
]

Week_9/Day 1/film_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.Homepage.as_view(), name='homepage'),
    path('addDirector', views.AddDirector.as_view(), name='AddDirector'),
    path('addFilm', views.AddFilm.as_view(), name='AddFilm'),
    # path('accounts', views.Homepage.as_view(), name='homepage'),    
]

Week_9/Day 1/film_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('homepage/', include('film_app.urls')),
    path('accounts/', include('account_app.urls')),
]

Week_9/Day 1/account_app/models.py
from django.db import models

# Create your models here.

Week_9/Day 1/film_app/models.py
from django.db import models

class Country(models.Model):
    name = models.CharField(max_length=100)
    
class Category(models.Model):
    name = models.CharField(max_length=100)
    
class Director(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)    
    
class Film(models.Model):
    title = models.CharField(max_length=100)
    release_date = models.DateField(auto_now_add=True)
    created_in_country = models.ForeignKey(Country, on_delete=models.CASCADE)
    category = models.ManyToManyField(Category)
    director = models.ManyToManyField(Director)
    

Week_9/Day 1/film_app/forms.py
from django.forms import ModelForm
from django import forms
from .models import Country, Category, Director, Film


class AddFilmForm(ModelForm):
    class Meta:
        model = Film
        fields = '__all__'


class AddDirectorForm(ModelForm):
    class Meta:
        model = Director
        fields = '__all__'

Week_9/Day 1/account_app/views.py
from django.shortcuts import render

def accounts(request):
    context={}
    return render(request, '../templates/accounts.html', context)

Week_9/Day 1/film_app/views.py
from django.shortcuts import render, redirect
from .models import Country, Category, Director, Film
from .forms import AddFilmForm, AddDirectorForm
from django.views import generic



class Homepage(generic.ListView):
    model = Film
    template_name = '../templates/homepage.html'
    
    
class AddFilm(generic.View):
    def get(self, request):
        form = AddFilmForm()
        context = {
            'form': form,
        }
        return render(request, '../templates/film/addFilm.html', context)
    
    def post(self, request):
        form = AddFilmForm(request.POST)
        
        if form.is_valid():
            form.save()
            
        return redirect('../templates/homepage.html')


class AddDirector(generic.View):
    def get(self, request):
        form = AddDirectorForm()
        context = {
            'form': form,
        }
        return render(request, '../templates/film/addDirector.html', context)
    
    def post(self, request):
        form = AddDirectorForm(request.POST)
        
        if form.is_valid():
            form.save()
            
        return redirect('../templates/homepage.html')

Week_9/Day 1/templates/accounts.html
{% extends 'base.html' %}

{% block content %}
    BlahBlah ACCOUNTS
{% endblock content %}

Week_9/Day 1/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel='stylesheet' href='https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css'> 
    <title>Document</title>
</head>
<body>

    {% include 'navbar.html' %}

    {% block content %}
    {% endblock content %}
    
</body>
</html>

Week_9/Day 1/templates/director/addDirector.html
{% extends 'base.html' %}


{% block content %}
<form method="POST">
    <div style="padding:20px">
        {% csrf_token %}
        <h1>Add a Director</h1>
        <table>
            {{form.as_table}}
        </table>
        <button type="submit">Save</button>
    </div>
</form>
{% endblock %}

Week_9/Day 1/templates/film/addFilm.html
{% extends 'base.html' %}


{% block content %}
<form method="POST">
    <div style="padding:20px">
        {% csrf_token %}
        <h1>Add a Film</h1>
        <table>
            {{form.as_table}}
        </table>
        <button type="submit">Save</button>
    </div>
</form>
{% endblock %}

Week_9/Day 1/templates/homepage.html
{% extends 'base.html' %}



{% block content %}
    <h1>All the new films</h1>
    {% if film_list %}
    {% for film in film_list %}
        {{film}}
        <a href="{% url 'addFilm' %}" class="btn btn-danger" >Add Question</a>
    {% endfor %}
    {% endif %}
    <a href="{% url 'home' %}" class="btn btn-primary" >Back to Home</a>

{% endblock content %}

Week_9/Day 1/templates/navbar.html
{% block navbar %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Dropdown
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#">Disabled</a>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>
  
{% endblock navbar %}