Week_10/YuGiOh_proj/forum/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.CommentListView.as_view(), name='comment_list'),
    path('comment/create/', views.CommentCreateView.as_view(), name='comment_create'),
    path('comment/<int:pk>', views.CommentDetailView.as_view(), name='comment_detail'),
    path('comment/<int:pk>/edit/', views.CommentUpdateView.as_view(), name='comment_update'),
    path('comment/<int:pk>/delete/', views.CommentDeleteView.as_view(), name='comment_delete'),
    path('comment/<int:pk>/reply/', views.ReplyCreateView.as_view(), name='reply_create'),
    ]

Week_10/YuGiOh_proj/yugioh_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.forms import AdminPasswordChangeForm

urlpatterns = [
    path('admin/', admin.site.urls),

    path('account/', include('django.contrib.auth.urls')),
    path('account/', include('account.urls')),
    path('forum/', include('forum.urls')),
    path('trading/', include('trading.urls')),
    path('', include('mainpage.urls')),
]

Week_10/YuGiOh_proj/forum/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse

User = get_user_model()

class Comment(models.Model):
    title = models.CharField(max_length=255)
    text = models.TextField()
    post_date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse('comment_detail', args=[str(self.id)])
    
class Reply(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    text = models.TextField()
    post_date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    def __str__(self):
        return self.text
    def get_absolute_url(self):
        return reverse('comment_detail', args=[str(self.id)])

Week_10/YuGiOh_proj/forum/forms.py
from django import forms
from forum.models import Reply, Comment

Week_10/YuGiOh_proj/forum/views.py
from django.shortcuts import render, redirect
from forum.models import Comment, Reply
from django.views.generic import View, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.utils import timezone
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin




class ReplyCreateView(LoginRequiredMixin, CreateView):
    model = Reply
    fields=['text']
    template_name='reply_create.html'

    
class CommentCreateView(LoginRequiredMixin, CreateView):
    model = Comment
    template_name = 'comment_create.html'
    fields = ['title','text']
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        return context
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
        
class CommentDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Comment
    success_url ="comment_list/"
    # def form_valid(self, form):
    #     form.instance.user = self.request.user
    #     return super().form_valid(form)

class CommentDetailView(DetailView):
    model = Comment
    template_name = 'comment_detail.html'
    fields = ['title','text', 'post_date', 'user']
        


class CommentListView(ListView):
    model = Comment
    template_name = 'comment_list.html'
    fields = ['title','text', 'post_date', 'user']




class CommentUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Comment
    template_name = 'comment_update.html'
    fields = ['title','text']
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        return context

Week_10/YuGiOh_proj/forum/templates/addcomment.html
{% extends 'base.html' %}

{% block title %}
Forum - {{ block.super }}
{% endblock title %}

{% block content %}
<h2>This is add comment html</h2>
{% if invalid_entry %}
Invalid entry
{% endif %}
<div id="changepassword-wrapper">
    <div id="changepassword-box">
        <form method="POST" class="form-signin">
            {% csrf_token %}
            {{form.as_p}}
            <button class="form-control btn btn-success" type='submit'>Post Comment</button>
        </form>
    </div>
</div>

<a href="{% url 'forum' %}" class="btn btn-primary">Back to Forum</a>
{% endblock content %}

Week_10/YuGiOh_proj/forum/templates/comment_create.html
{% extends 'base.html' %}

{% block title %}
Forum - {{ block.super }}
{% endblock title %}

{% block content %}
<h2>This is add comment html</h2>

<div id="comment-create-wrapper">
    <div id="comment-create-box">
        <form method="POST" action="">
            {% csrf_token %}
            {{form.as_p}}
            <button class="form-control btn btn-success" type='submit'>Post Comment</button>
        </form>
    </div>
</div>

<a href="{% url 'forum' %}" class="btn btn-primary">Back to Forum</a>
{% endblock content %}

Week_10/YuGiOh_proj/forum/templates/comment_delete.html
{% extends 'base.html' %}

{% block content %}
<div id="comment-delete-form-wrapper">
    <div id="comment-delete-form-box">
        <form method="post">
            {% csrf_token %}
            <p>Are you sure you want to delete the selected comment?</p>
            <input class='btn btn-danger' type="submit" value="Confirm">
        </form>
    </div>
</div>

{% endblock content %}

Week_10/YuGiOh_proj/forum/templates/comment_detail.html
{% extends 'base.html' %}


{% block content %}
<div class="comment-wrapper">
    <div class="comment-box mt-2 ml-4">

        <div class="card">

            <div class="card-header text-left">
                <span class="font-weight-bold"><a href="{% url 'comment_detail' object.pk %}">{{object.title}}</a></span> &middot;
                <span class="text-muted">by {{object.user}} | {{object.post_date}}</span>
            </div>

            <div class="card-body text-left">
                <p>{{object.text}}</p>
            </div>
            <a href="{% url 'reply_create' object.pk %}" class="btn btn-success">Reply</a>
            
            {% ifequal user object.user %}
            <div class="card-footer text-center text-muted">
                <a href="{% url 'comment_update' object.pk %}" class="btn btn-primary">Edit Comment</a>
                <a href="{% url 'comment_delete' object.pk %}" class="btn btn-primary">Delete Comment</a>
            </div>
            {% endifequal %}

        </div>


        {% if object.reply_set %}
            {% for reply in object.reply_set.all %}
                <div class="card mt-2 ml-4">
                    <div class="card-header">
                        <span class="text-muted">reply by {{object.user}} | {{object.post_date}}</span>
                    </div>
                    <div class="card-body">
                        <p class="text-left">{{reply.text}}</p>
                    </div>
                </div>
            {% endfor %}
        {% endif %}
    </div>
</div>
{% endblock content %}

Week_10/YuGiOh_proj/forum/templates/comment_list.html
{% extends 'base.html' %}

{% block title %}
Forum - {{ block.super }}
{% endblock title %}

{% block content %}
<h1>Comments</h1>
<div>
    <a href="{% url 'comment_create' %}" class="btn btn-primary">Add Comment</a>
    <a href="{% url 'mainpage' %}" class="btn btn-primary">Back to Mainpage</a>
</div>

<div id="comment-detail-wrapper">
    <div id="comment-detail-box">
        {% for object in object_list %}
        <div class="card mt-2 ml-4">
            <div class="card-header text-left">
                <span class="font-weight-bold"><a href="{% url 'comment_detail' object.pk %}">{{object.title}}</a></span> &middot;
                <span class="text-muted">by {{object.user}} | {{object.post_date}}</span>
            </div>
            <div class="card-body text-left">
                <p>{{object.text}}</p>
            </div>
            <div class="card-footer">
                <p>
                    <a href="{% url 'comment_detail' object.pk %}">Replies: {{object.reply_set.all.count}}</a>
                </p>
                {% ifequal user object.user %}
                <p>
                    <a href="{% url 'comment_update' object.pk %}" class="btn btn-primary">Edit Comment</a> |
                    <a href="{% url 'comment_delete' object.pk %}" class="btn btn-primary">Delete Comment</a>
                </p>
                {% endifequal %}
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock content %}

Week_10/YuGiOh_proj/forum/templates/comment_snippet.html
<p>{{object.text}}</p>
<p>{{object.post_date}}</p>
<p>{{object.user}}</p>

Week_10/YuGiOh_proj/forum/templates/comment_update.html
{% extends 'base.html' %}

{% block title %}
Forum - {{ block.super }}
{% endblock title %}

{% block content %}
<h2>Update Comment</h2>

<div id="comment-create-wrapper">
    <div id="comment-create-box">
        <form method="POST" action="">
            {% csrf_token %}
            {{form.as_p}}
            <button class="form-control btn btn-success" type='submit'>Post Comment</button>
        </form>
    </div>
</div>

<a href="{% url 'forum' %}" class="btn btn-primary">Back to Forum</a>
{% endblock content %}

Week_10/YuGiOh_proj/forum/templates/reply_create.html
{% extends 'base.html' %}

{% block title %}
Reply - {{ block.super }}
{% endblock title %}

{% block content %}
<div id="reply-create-wrapper">
    <div id="reply-create-box">
        <form method="POST" action="">
            {% csrf_token %}
            {{form.as_p}}
            <button class="form-control btn btn-success" type='submit'>Post Reply</button>
        </form>
    </div>
</div>

<a href="{% url 'comment_list' %}" class="btn btn-primary">Back to Forum</a>
{% endblock content %}